command_timeout = 1000
# ~/.config/starship.toml
[shell]
disabled = false
bash_indicator = "ğŸ’©"
fish_indicator = "ğŸ "
nu_indicator = ""

[env_var.CUSTOMER]
default = ""
format = "[$env_value]($style)"

[env_var.ENV]
symbol = " "
format = "$symbol[$env_value]($style)"

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_branch]
symbol = "ğŸŒ± "

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "â•"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[gcloud]
symbol = "ğŸ§¿"
format = '[$symbol$account(@$domain)(\($project\))]($style) '
[gcloud.region_aliases]
europe-west3 = "frankfurt"

[azure]
disabled = false
format = "on [$symbol($subscription)]($style) "
symbol = "ğŸŒŠ"
style = "blue bold"

[kubernetes]
format = 'on [â˜¸ $context](dimmed blue) '
disabled = false
[kubernetes.context_aliases]
"aks-plattform42-prod-noea" = "enova-prod ï¸ğŸš¨"
"aks-plattform42-dev-noea" = "enova-dev"
