command_timeout = 1000
# ~/.config/starship.toml

[aws]
disabled = true

[character]
success_symbol = ""
error_symbol = ""

[shell]
disabled = false
bash_indicator = "ğŸ’©"
fish_indicator = ""
nu_indicator = ""

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_branch]
symbol = "ğŸŒ± "

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "â•"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[gcloud]
disabled = true
# symbol = "ğŸ§¿"
# format = '[$symbol$account(@$domain)(\($project\))]($style) '
# [gcloud.region_aliases]
# europe-west3 = "frankfurt"

[azure]
disabled = true
# format = "on [$symbol($subscription)]($style) "
# symbol = "ğŸŒŠ"
# style = "blue bold"

[java]
# symbol = "ğŸ…º "
symbol = "â˜•"

[kubernetes]
disabled = true
# format = 'on [â˜¸ $context](dimmed blue) '
# disabled = false
# [kubernetes.context_aliases]
# "aks-plattform42-prod-noea" = "enova-prod ï¸ğŸš¨"
# "aks-plattform42-dev-noea" = "enova-dev"

[package]
disabled = true

[ruby]
symbol = "ğŸ’ "

[rust]
symbol = "ğŸ¦€ "
